export const firstList = [
  { src: require("../../assets/location.png"), name: "Track Order" },
  { src: require("../../assets/resize.png"), name: "Size Chart" },
  { src: require("../../assets/notification.png"), name: "Notifications" },
  { src: require("../../assets/store.png"), name: "Store Locator" },
  {
    src: require("../../assets/country.png"),
    name: "Country",
    flag: require("../../assets/flag.png"),
    country: "USD",
  },
  {
    src: require("../../assets/translate.png"),
    name: "Language",
    language: "ENG",
  },
  { src: require("../../assets/aboutUs.png"), name: "About Us" },
  { src: require("../../assets/faq.png"), name: "FAQ" },
  { src: require("../../assets/shipping.png"), name: "Shipping & Return" },
  { src: require("../../assets/chat.png"), name: "Chat With Us" },
  { src: require("../../assets/rate.png"), name: "Rate Application" },
  { src: require("../../assets/thumbsUp.png"), name: "Share Application" },
  { src: require("../../assets/policy.png"), name: "Privacy Policy" },
  { src: require("../../assets/terms.png"), name: "Terms & Conditions" },
  { src: require("../../assets/email.png"), name: "Send Us An Email" },
];
